# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  name: prometheus
  namespace: kube-system
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
  - watch
