{
 "title": "OCS - Disks",
 "description": "graphs for disk operation",
 "tags": [
  "prometheus",
  "ocs",
  "disks"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"node_exporter\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bytes - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Ops - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Ops - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Time - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Time - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Merged - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged_total{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Merged - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_merged_total{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}