{
 "title": "OCS - Disks - Block Devices",
 "description": "graphs for disk operation",
 "tags": [
  "prometheus",
  "ocs",
  "disks"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(pvc_namespace_map, exported_namespace)"
   },
   {
    "name": "pvc",
    "label": "pvc",
    "query": "label_values(pvc_namespace_map{exported_namespace=\"$namespace\"}, pvc)"
   },
   {
    "name": "pv",
    "label": "pv",
    "query": "label_values(pvc_namespace_map{exported_namespace=\"$namespace\", pvc=\"$pvc\"}, pv)"
   },
   {
    "name": "dm",
    "label": "dm",
    "query": "label_values(device_map{pv=\"$pv\"}, dm)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(device_map{pv=\"$pv\", dm=\"$dm\"}, node)"
   },
   { "name": "port", "label": "port", "query": "${VAR_PORT}" }
  ]
 },
 "panels": [
  {
   "title": "Bytes - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"node-exporter\",instance=~\"$node:$port\",device=\"$dm\"}[5m])",
     "legendFormat": "{{$pvc}} - {{$node}} - {{$dm}}"
    }
   ]
  },
  {
   "title": "Bytes - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"node-exporter\",instance=~\"$node:$port\",device=\"$dm\"}[5m])",
     "legendFormat": "{{$pvc}} - {{$node}} - {{$dm}}"
    }
   ]
  },
  {
   "title": "Ops - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"node-exporter\",instance=~\"$node:$port\",device=\"$dm\"}[5m])",
     "legendFormat": "{{$pvc}} - {{$node}} - {{$dm}}"
    }
   ]
  },
  {
   "title": "Ops - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"node-exporter\",instance=~\"$node:$port\",device=\"$dm\"}[5m])",
     "legendFormat": "{{$pvc}} - {{$node}} - {{$dm}}"
    }
   ]
  },
  {
   "title": "Time - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node-exporter\",instance=~\"$node:$port\",device=\"$dm\"}[5m])",
     "legendFormat": "{{$pvc}} - {{$node}} - {{$dm}}"
    }
   ]
  },
  {
   "title": "Time - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node-exporter\",instance=~\"$node:$port\",device=\"$dm\"}[5m])",
     "legendFormat": "{{$pvc}} - {{$node}} - {{$dm}}"
    }
   ]
  },
  {
   "title": "Merged - read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged_total{job=\"node-exporter\",instance=~\"$node:$port\",device=\"$dm\"}[5m])",
     "legendFormat": "{{$pvc}} - {{$node}} - {{$dm}}"
    }
   ]
  },
  {
   "title": "Merged - write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_merged_total{job=\"node-exporter\",instance=~\"$node:$port\",device=\"$dm\"}[5m])",
     "legendFormat": "{{$pvc}} - {{$node}} - {{$dm}}"
    }
   ]
  }
 ]
}