{
 "title": "OCS - Heketi",
 "tags": [
  "ocs",
  "heketi",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(heketi_up, service)"
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": "label_values(heketi_device_count{service=\"$service\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heketi Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_up{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Cluster Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_cluster_count{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_nodes_count{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "heketi_volumes_count{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "content": "This dashboard displays metrics from OpenShift Container Storage (OCS)\n\nFor more information, check [project/glusterfs](https://console.paas.dc1.rhbrlab.com/console/project/glusterfs/overview)"
  },
  {
   "title": "$hostname - Storage Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "heketi_device_size {hostname=~\"$hostname\"}",
     "legendFormat": "total size {{device}}"
    },
    {
     "expr": "heketi_device_used {hostname=~\"$hostname\"}",
     "legendFormat": "used {{device}}"
    }
   ]
  },
  {
   "title": "Volumes Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes"
    }
   ]
  }
 ]
}